Display fatal_dialog when dashboard generation fails
att/rcloud.flexdashboard pull request #17
Opened 2017-04-19 08:48 UTC by useless5771

As a first iteration I implemented the 'good start' solution: the fatal_dialog is displayed and holds the stack-trace and the 'loading' panel is removed. So when user clicks the 'close' button on the fatal_dialog they will be presented with a blank page.

![capture](https://cloud.githubusercontent.com/assets/578443/25171323/6237dfd4-24e5-11e7-90d5-fa15e691a1d2.PNG)

The error is handled by JS Promise exception handling.  

The other possibility to fix this issue would be to make the render.R catch the exception thrown by rmarkdown::render function and display the fatal_dialog from there...

Much improvement could be made here:
* Display the error message directly on the page, not in fatal_error.
* Display the 

error message and stack-trace separately - so users are presented with a simple message by default and they can view the stack trace on request. This would rather require the latter approach, as rserve.js concatenates the error message and the stacktrace so these then would have to be split... Also the stack-trace holds too-much information - includes rserve calls as well, which are useful for debugging but may not be that useful for end-users.

2017-04-19 14:43 UTC, gordonwoodhull commented
Those are great points about displaying error messages in a friendly way. I think when we introduced stack traces we were just so happy to finally get the details, that we didn't think about how to make them less intimidating for users. 

We definitely want to make the detailed stack trace easy to access so that when users report bugs, they can paste the details to us.

If that's something you're interested in helping with, I think the changes would be better made as part of RCloud core - e.g. we could add a higher-level error display function which does special formatting for stack traces.

As for this patch, it does work for errors within the notebook (so it fixes most of #14), but it doesn't fix #13. To test this, open the flexdashboard page in a new tab. Then log out of RCloud in your original tab and reload the flexdashboard. Still just blinking heart.

You should see an obscure error message currently (as shown in #12/#13). I think that we need to restore the ocap by reverting att/rcloud#857 but I'm waiting for feedback on that. Then we'll need to improve the error message by actually checking if the notebook is loadable on the R side, but we can do that separately. First step is just to get the error to appear.

2017-04-20 12:33 UTC, useless5771 commented
Thank you for your feedback. Yes, I haven't tested the initial change against #13 as I sort of assumed that it is a separate problem. Now I have added an error handling for the anonymous access to flex dashboard. It simply checks if module loading is available, and if it isn't an error is thrown and displayed in the fatal_dialog. I also tested it with published notebook and the behavior is the same.

Yes, I could have a look at how the errors are produced by rcloud core and possibly to improve the fatal_dialog (so the error message and stacktrace are displayed separately). This would let us process the error messages up the call stack, provide contextual information to error messages and apply some formatting. I guess we would need an improvement ticket for this?

2017-04-20 14:56 UTC, gordonwoodhull commented
We're pretty informal in how we manage issues in RCloud. Partly because the managers are developers too, and partly because there is an infinite amount of work to do and hundreds of open tickets. 

Please open an issue on RCloud with your proposal, and @s-u and I can comment on it.

2017-04-20 15:03 UTC, gordonwoodhull requested changes
Don't bother with the extra check for a bug condition - the important thing is just to report all errors.

2017-04-20 15:03 UTC, gordonwoodhull commented on inst/www/js/rcloud-flexdashboard.js
> +                }
This isn't really necessary because it's just a bug in RCloud or this package and it doesn't really matter what error we display.

2017-04-20 15:03 UTC, gordonwoodhull commented on inst/www/js/rcloud-flexdashboard.js
> +            promise = promise.catch(onError);
This is the important line - we just don't want to lose errors for any reason.

2017-04-20 15:50 UTC, gordonwoodhull commented
Thanks @useless5771, good work. Looks ready to merge. I'll test it tomorrow and go for it.

I've assigned you a bunch of issues across the `rcloud.*` RStudio compatibility packages. Feel free to work on stuff in any order that suits you, and please comment on the tickets or send me email if you have any questions.

2017-04-20 16:20 UTC, useless5771 commented
Ok, great, thanks.

2017-04-24 10:42 UTC, useless5771 commented
Changeset for issue #11 got included in this pull request, sorry about that.

2017-04-24 19:33 UTC, merged

2017-04-24 19:38 UTC, gordonwoodhull commented
Thanks @useless5771! Merged and will go into the next package release.